### ISSUE TITLE
wird iqontrol noch gepflegt

### ISSUE THREAD

**Issue by Marty56** [iobroker-community-adapters/ioBroker.iqontrol#299]
Hallo,

Mich würde interessieren, ob  dieser Adapter noch weiter fehlerbereinigt wird oder der Entwickler aufgehört hat?

**Comment by mllrmnn** [comment]
Hi, ich habe folgendes in Forum gelesen: [https://forum.iobroker.net/post/1010253](https://forum.iobroker.net/post/1010253)

**Comment by mcm1957** [comment]
Sorry, sieht im Moment nicht danach aus :-(

Siehe auch https://github.com/sbormann/ioBroker.iqontrol/issues/313
