### ISSUE TITLE
Wird iQontrol noch Gepflegt/Weiterentwickelt? 

### ISSUE THREAD

**Issue by HansMann18** [iobroker-community-adapters/ioBroker.iqontrol#308]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by HansMann18** [comment]
Hallo, kann mir jemand sagen, ob iQontrol noch gepflegt wird ?
Es gibt einige Fehler, die ich in einigen Foren angesprochen habe.
Komischerweise meldet sich sbormann nicht mehr!
Hat jemand eine Antwort für mich?

**Comment by mcm1957** [comment]
Sorry, sieht im Moment nicht danach aus :-(

Siehe auch https://github.com/sbormann/ioBroker.iqontrol/issues/313
